[package]
name = "wasm-mb"
version = "0.1.0"
edition = "2021"
description = "Yew Microblog using Trunk"
readme = "README.md"
repository = "https://github.com/jakenherman/wasm-mb"
keywords = ["yew", "trunk", "wasm"]
categories = ["wasm", "microblog", "rust"]

[dependencies]
yew = "0.19"